#! /bin/bash 

# hack to be able to execute the cmakeMain, cmakeSrc, cmakeInclude files in only current session.
export PATH="$PATH:$SCRIPTS_LIB_PATH/cppProject_include"

# Adding git to project
git init
echo "
# ignore all files except the CMakeList.txt file if using UnitTest++ framework.
# UnitTest++/src/*.cpp
# UnitTest++/src/*.h
# UnitTest++/src/*.o
# UnitTest++/src/cmake-build-debug/*
# UnitTest++/src/Posix/*
# UnitTest++/src/.idea
# UnitTest++/libUnitTest++.a
# UnitTest++/src/tests/*
# UnitTest++/src/*.d
build/*
" > .gitignore

# adding unit tests to project
cp -r $SCRIPTS_LIB_PATH/googletest/ .

# Creating root CMakeLists.txt file
if [[ "$1" == '-wx' ]]; then
    cmakeWxWidgets
else 
    cmakeMain
fi

# adding all directories
mkdir build include src 

# Setting up the source file directory CMakeLists.txt and main.cpp entry file
cd src
cmakeSrc
touch main.cpp 

# setting up include directory
cd ../include
cmakeInclude
cd ..

# Adding README.md to the Root.
echo " 
## PROJECT 
----

" > README.md


