#! /bin/bash 

# hack to be able to execute the cmakeMain, cmakeSrc, cmakeInclude files in only current session.
export PATH="$PATH:$SCRIPTS_LIB_PATH/cppProject_include"

# ASSERT ----------------------------------------------------------------------
# Testing the current directory for any other directories or files that match 
# the ones we are creating here. This is to not override the existing files and
# loose work

# run assert script
assert_no_existing_files_or_Dirs

# test assert exit status
if [ $? -eq 1 ] ; then
    exit 1
fi

# -----------------------------------------------------------------------------

# Adding git to project
git init

# adds gitIgnore file with preset ignore files.
gitIgnore

# Creating root CMakeLists.txt file
if [[ "$1" == '-wx' ]]; then
    cmakeWxWidgets
else 
    cmakeMain
fi

# adding all directories
mkdir build include src 

# Setting up the source file directory CMakeLists.txt and main.cpp entry file
cd src
cmakeSrc
touch main.cpp 

# setting up include directory
cd ../include
cmakeInclude
cd ..

# Adding README.md to the Root.
echo " 
## PROJECT 
----

" > README.md

# adding googletest to project
git clone https://github.com/google/googletest.git -b v1.13.0
cd googletest        # Main directory of the cloned repository.
mkdir build          # Create a directory to hold the build output.
cd build
cmake ..             # Generate native build scripts for GoogleTest.
cd ../../


