#!/bin/bash

ipconfig.exe | awk 'BEGIN { print "Windows IP Configuration:" }
/IPv6 Address/ { print "\nLink-local IPv6 Address . . . . . : ", $NF }
/IPv4 Address/ { print "IPv4 Address. . . . . . . . . . . : ", $NF }
/Subnet Mask/  { print "Subnet Mask . . . . . . . . . . . : ", $NF }
/Gateway/      { print "Default Gateway . . . . . . . . . : ", $NF }
/DNS Servers/  { print "DNS . . . . . . . . . . . . . . . : ", $NF }
/DHCP Enabled/ { print "DNS Enabled . . . . . . . . . . . : ", $NF }'


