#!/bin/bash

# This script prints the current time in 24-hour format

current_time=$(date +"%H:%M:%S")  # %H, %M, %S format specifiers for hour, minute, second in 24-hour format
echo -e "The current time is:\t$current_time"

